# Generated by Django 5.0.1 on 2024-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nomeCompleto',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome Completo'),
        ),
    ]
