# Generated by Django 5.0.1 on 2024-01-25 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('tipo', models.CharField(choices=[('Medicamento', 'Medicamento'), ('Alimento', 'Alimento'), ('Limpeza', 'Limpeza')], max_length=20)),
                ('marca', models.TextField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('dataFabricacao', models.DateField()),
                ('dataValidade', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fardos', to='meuApp.produto')),
            ],
        ),
    ]
