# Generated by Django 5.0.1 on 2024-01-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('dataFabricacao', models.DateField()),
                ('dataValidade', models.DateField()),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fardos', to='meuApp.produto')),
            ],
        ),
    ]
