# Generated by Django 5.0.1 on 2024-01-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='codProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fardos', to='meuApp.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='dataFabricacao',
            field=models.DateField(verbose_name='Data de Fabricação'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='dataValidade',
            field=models.DateField(verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
    ]
