# Generated by Django 5.0.1 on 2024-01-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0002_alter_estoque_codproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.BinaryField(blank=True, null=True, verbose_name='Imagem'),
        ),
    ]
