# Generated by Django 5.0.1 on 2024-01-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/produtos/', verbose_name='Imagem'),
        ),
    ]
