# Generated by Django 5.0.1 on 2024-02-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem'),
        ),
    ]
